import Head from 'next/head';
import {useEffect,useRef,useState} from 'react';
import {FEATURES} from '../../lib/platform-schema';
import css from '../../styles/platform-admin.module.css';
const ENDPOINT='/api/hero-admin/platform';
const TABS=[['overview','Resumen'],['usage','Interacciones'],['audience','Audiencia'],['controls','Controles'],['history','Historial'],['health','Diagnóstico']];
const NAMES={page_view:'Página vista',game_open:'Abrir Emotion Rush',game_restart:'Reiniciar partida',game_share:'Compartir partida',bag_search:'Buscar moneda',bag_reset_request:'Solicitar reset',bag_share:'Compartir bolsa',bag_suggestion:'Elegir sugerencia',bag_edit:'Editar posición',bag_add_purchase:'Agregar compra',market_share:'Compartir mercado',bubble_open:'Abrir Bubble Maps',bubble_expand:'Expandir mapa',hero_open:'Ver personaje',token_search:'Buscar token',pulse_open:'Abrir Pulse',character_style:'Cambiar estilo',coin_open:'Consultar moneda',timeframe_change:'Cambiar periodo',market_tab:'Cambiar lista',studio_action:'Acción en Studio',welcome_explore:'Explorar emoción',dashboard_open:'Entrar al dashboard',hero:'Hero 3D',market:'Mercado',bagMood:'Bag Mood',radar:'Emotion Radar',tokenExplorer:'Token Explorer',studio:'Studio',game:'Emotion Rush',scale:'Escala emocional',desktop:'Escritorio',mobile:'Móvil',tablet:'Tablet',direct:'Directo / sin referencia'};
const number=n=>new Intl.NumberFormat('es',{maximumFractionDigits:1}).format(Number(n)||0);
const date=d=>d?new Date(d).toLocaleString('es'):'Todavía sin datos';
function Empty(){return <p className={css.empty}>Todavía no hay datos en este periodo. Se mostrarán cuando lleguen visitas con la medición autorizada.</p>;}
function Bars({rows=[],suffix=''}){const max=Math.max(1,...rows.map(r=>Number(r.value)));return rows.length?<ul className={css.bars}>{rows.map(r=><li key={r.name}><div><span>{NAMES[r.name]||r.name}{suffix}</span><strong>{number(r.value)}</strong></div><div className={css.track}><i style={{width:`${Number(r.value)/max*100}%`}}/></div></li>)}</ul>:<Empty/>;}
function Chart({rows=[],days}){
 const map=Object.fromEntries(rows.map(r=>[r.day,r]));const count=days+1;const data=Array.from({length:count},(_,i)=>{const day=new Date(Date.now()-(count-i-1)*86400000).toISOString().slice(0,10);return map[day]||{day,views:0,sessions:0};});
 const max=Math.max(1,...data.map(r=>r.views));const x=i=>42+i/(count-1)*710,y=n=>180-n/max*145;
 if(!rows.length)return <Empty/>;
 return <><svg className={css.chart} viewBox="0 0 780 215" role="img" aria-label="Páginas vistas y sesiones por día UTC"><title>Páginas vistas y sesiones. Consulta los valores exactos en la tabla inferior.</title>{[0,.5,1].map(n=><g key={n}><line x1="42" x2="752" y1={y(n*max)} y2={y(n*max)} stroke="#293b45"/><text x="5" y={y(n*max)+4} fill="#8ca3ae" fontSize="11">{number(n*max)}</text></g>)}<polyline fill="none" stroke="#88e5b8" strokeWidth="3" points={data.map((r,i)=>`${x(i)},${y(r.views)}`).join(' ')}/><polyline fill="none" stroke="#77a9ee" strokeWidth="2" points={data.map((r,i)=>`${x(i)},${y(r.sessions)}`).join(' ')}/>{data.map((r,i)=><circle key={r.day} cx={x(i)} cy={y(r.views)} r="4" fill="#88e5b8"><title>{r.day}: {r.views} páginas · {r.sessions} sesiones</title></circle>)}<text x="42" y="207" fill="#8ca3ae" fontSize="11">{data[0].day}</text><text x="752" y="207" textAnchor="end" fill="#8ca3ae" fontSize="11">{data.at(-1).day}</text></svg><div className={css.legend}><span>● Páginas vistas</span><span>● Sesiones</span></div><details><summary>Ver tabla de datos</summary><div className={css.tableWrap}><table><thead><tr><th>Día UTC</th><th>Páginas</th><th>Sesiones</th><th>Clics</th></tr></thead><tbody>{data.map(r=><tr key={r.day}><td>{r.day}</td><td>{r.views}</td><td>{r.sessions}</td><td>{r.clicks||0}</td></tr>)}</tbody></table></div></details></>;
}
function Card({title,sub,children,wide=false}){return <section className={`${css.card} ${wide?css.wide:''}`}><h2>{title}</h2>{sub&&<p className={css.sub}>{sub}</p>}{children}</section>;}
export default function PlatformAdmin(){
 const [auth,setAuth]=useState(null),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [tab,setTab]=useState('overview'),[days,setDays]=useState(7),[data,setData]=useState(null),[state,setState]=useState(null),[draft,setDraft]=useState(null),[history,setHistory]=useState([]),[note,setNote]=useState('');
 const sequence=useRef(0),mounted=useRef(true);
 const dirty=!!state&&JSON.stringify(draft)!==JSON.stringify(state.config);
 async function request(url,body){const r=await fetch(url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store',signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok){if(r.status===401)setAuth(false);throw Error(d.error||'No se pudo completar la solicitud');}return d;}
 async function loadState(){try{const s=await request(ENDPOINT);if(!mounted.current)return;setState(s);setDraft(s.config);setAuth(true);try{localStorage.setItem('wmAnalyticsAdmin','1');}catch{}}catch(e){if(mounted.current)setError(e.message);}}
 async function loadReport(){const seq=++sequence.current;try{const report=await request(`${ENDPOINT}?action=report&days=${days}`);if(mounted.current&&seq===sequence.current){setData(report);setError('');}}catch(e){if(mounted.current&&seq===sequence.current)setError(e.message);}}
 async function loadHistory(){try{const h=await request(ENDPOINT+'?action=history');setHistory(h.items);}catch(e){setError(e.message);}}
 useEffect(()=>{mounted.current=true;loadState();return()=>{mounted.current=false;sequence.current++;};},[]);
 useEffect(()=>{if(!auth)return;loadReport();loadHistory();const timer=setInterval(()=>{if(!document.hidden)loadReport();},60000);return()=>{clearInterval(timer);sequence.current++;};},[auth,days]);
 useEffect(()=>{if(!dirty)return;const warn=e=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 async function login(e){e.preventDefault();setBusy(true);setError('');try{await request('/api/hero-admin',{action:'login',password});setPassword('');await loadState();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function logout(){if(dirty&&!confirm('¿Salir y descartar los cambios sin publicar?'))return;try{await request('/api/hero-admin',{action:'logout'});setAuth(false);setData(null);}catch(e){setError(e.message);}}
 async function save(){if(!dirty)return;if(note.trim().length<3){setError('Escribe el motivo del cambio.');return;}if(!confirm('¿Publicar estos cambios para todos los visitantes?'))return;setBusy(true);setError('');try{const s=await request(ENDPOINT,{action:'publish',config:draft,revision:state.revision,note});setState({revision:s.revision,config:s.config,updated_at:s.created_at});setDraft(s.config);setNote('');setNotice('Publicado. Los visitantes recibirán los cambios en aproximadamente 30 segundos.');loadHistory();}catch(e){setError(e.message);}finally{setBusy(false);}}
 function exportCSV(){if(!data)return;const rows=[['grupo','nombre','valor'],...['pages','actions','sections','sources','devices','browsers','scroll','vitals'].flatMap(k=>data[k].map(r=>[k,r.name,r.value])),...data.daily.flatMap(r=>[['daily_views',r.day,r.views],['daily_sessions',r.day,r.sessions],['daily_clicks',r.day,r.clicks]])];const safe=v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`wojakmeter-analytics-${days}d.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const totals=data?.totals||{};
 return <div className={css.root}><Head><title>Control Center · WojakMeter</title><meta name="robots" content="noindex,nofollow"/><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Archivo:wght@500;600;700&amp;family=Inter:wght@400;500;600;700&amp;family=IBM+Plex+Mono:wght@400;500&amp;display=swap"/></Head>
 {auth!==true?<main className={css.login}><span className={css.kicker}>WOJAKMETER / CONTROL CENTER</span><h1>Tu plataforma.<br/>En perspectiva.</h1><p>Usa la contraseña de Hero Studio para administrar WojakMeter.</p>{error&&<div className={css.error} role="alert">{error}</div>}<form onSubmit={login}><label>Contraseña<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} maxLength={256} required/></label><button disabled={busy}>{busy?'Conectando…':'Entrar al panel'}</button></form><a href="/">Volver al sitio</a></main>:<>
 <aside className={css.sidebar}><a className={css.brand} href="/admin">WOJAK<span>METER</span><small>CONTROL CENTER</small></a><nav aria-label="Secciones de administración">{TABS.map(([id,label],i)=><button key={id} className={tab===id?css.selected:''} aria-current={tab===id?'page':undefined} onClick={()=>{setTab(id);setNotice('');}}><span>0{i+1}</span>{label}{id==='controls'&&dirty?' •':''}</button>)}</nav><div className={css.sideLinks}><a href="/admin/hero">↗ Hero Studio</a><a href="/dashboard" target="_blank" rel="noreferrer">↗ Ver sitio</a><button onClick={logout}>Cerrar sesión</button></div><p className={css.sideNote}>Las visitas de este navegador están excluidas de la medición.</p></aside>
 <main className={css.main}><header className={css.header}><div><span className={css.kicker}>OBSERVA · ENTIENDE · MEJORA</span><h1>{TABS.find(t=>t[0]===tab)[1]}</h1><p>Datos propios. Decisiones con contexto.</p></div><div className={css.live}><i/> {number(data?.live)} sesiones en 5 min<small>{data?'Actualizado '+date(data.generatedAt):'Cargando métricas…'}</small></div></header>
 {error&&<div className={css.error} role="alert">{error} <button onClick={()=>{loadReport();}}>Reintentar métricas</button></div>}{notice&&<div className={css.notice} role="status">{notice}</div>}
 <div className={css.toolbar}><label>Periodo<select value={days} onChange={e=>{setData(null);setDays(Number(e.target.value));}}>{[1,7,30,90].map(n=><option key={n} value={n}>Últimos {n===1?'24 horas':n+' días'}</option>)}</select></label><span>Ventana móvil · días en UTC · solo sesiones con consentimiento</span><button onClick={exportCSV} disabled={!data}>Exportar CSV</button><button onClick={loadReport}>Actualizar</button></div>
 {tab==='overview'&&<><div className={css.metrics}>{[['Páginas vistas',totals.views,'Cargas y navegación interna'],['Sesiones medidas',totals.sessions,'No equivale a personas únicas'],['Clics en funciones',totals.clicks,'Interacciones instrumentadas'],['Tiempo activo / sesión',totals.sessions?number(totals.active_seconds/totals.sessions)+' s':'—','Tiempo visible y con foco, aproximado']].map(([name,value,desc])=><section key={name}><span>{name}</span><strong>{typeof value==='string'?value:number(value)}</strong><small>{desc}</small></section>)}</div><div className={css.grid}><Card title="La actividad de tu plataforma" sub="Evolución diaria de las visitas registradas." wide><Chart rows={data?.daily} days={days}/></Card><Card title="Páginas más vistas"><Bars rows={data?.pages}/></Card><Card title="Qué despierta interés" sub="Clics registrados; abrir un formulario no significa completarlo."><Bars rows={data?.actions?.slice(0,6)}/></Card></div></>}
 {tab==='usage'&&<div className={css.grid}><Card title="Interacciones por función" sub="Acciones identificadas en botones reales de la plataforma."><Bars rows={data?.actions}/></Card><Card title="Secciones consultadas" sub="Sesiones donde al menos 10% de la sección entró en pantalla."><Bars rows={data?.sections}/></Card><Card title="Profundidad de lectura" sub="Sesiones que alcanzaron cada porcentaje de desplazamiento. No es un embudo de compra."><Bars rows={data?.scroll} suffix="%"/></Card><Card title="Cómo interpretar estos datos"><p>Compara qué secciones se ven con qué acciones se usan. Mucha exposición y pocos clics puede indicar que el siguiente paso necesita ser más claro.</p><p>Se cuenta el uso del sitio público, no actividad dentro del iframe 3D ni operaciones del bot. Las solicitudes de reset y las compras editadas se miden como clics, nunca como valores monetarios.</p></Card></div>}
 {tab==='audience'&&<div className={css.grid}><Card title="Origen de las visitas" sub="Dominio de referencia. Sin rutas privadas, búsquedas ni parámetros."><Bars rows={data?.sources}/></Card><Card title="Dispositivos"><Bars rows={data?.devices}/></Card><Card title="Navegadores"><Bars rows={data?.browsers}/></Card><Card title="Qué significa una sesión"><p>Una sesión utiliza un identificador aleatorio por pestaña, renovado después de 30 minutos sin actividad registrada o al cerrar la pestaña.</p><p>No identificamos personas, ni cruzamos dispositivos. Se excluyen el administrador, Desk, solicitudes con señales de privacidad y agentes automatizados reconocibles. Los bloqueadores y quienes rechazan la medición no aparecen.</p></Card></div>}
 {tab==='controls'&&draft&&<><div className={css.grid}><Card title="Funciones públicas" sub="Cambios globales sin volver a compilar. Ocultar una sección no borra sus datos." wide><div className={css.features}>{Object.entries(FEATURES).map(([key,f])=><label className={css.feature} key={key}><div><strong>{f.label}</strong><small>{['game','pulse'].includes(key)?'Visibilidad + bloqueo de nuevos envíos en la API':'Visibilidad de la sección en el dashboard'}</small></div><input type="checkbox" role="switch" checked={draft.features[key]} onChange={e=>setDraft({...draft,features:{...draft.features,[key]:e.target.checked}})}/></label>)}</div><p className={css.sub}>Estos controles no detienen órdenes ni posiciones de Binance. El trading conserva su administración independiente en Desk. Ocultar módulos de lectura no detiene sus consultas de datos.</p></Card><Card title="Medición"><label className={css.feature}><div><strong>Analítica del sitio</strong><small>Solo se recopila con autorización del visitante.</small></div><input type="checkbox" role="switch" checked={draft.analyticsEnabled} onChange={e=>setDraft({...draft,analyticsEnabled:e.target.checked})}/></label><p>Desactivar detiene la recepción de nuevos eventos. El historial existente se conserva hasta su vencimiento.</p></Card><Card title="Aviso público"><label>Mensaje breve<textarea rows={3} maxLength={180} value={draft.announcement} onChange={e=>setDraft({...draft,announcement:e.target.value})}/></label><small>{draft.announcement.length}/180 · Vacío para ocultar.</small>{draft.announcement&&<div className={css.notice}>{draft.announcement}</div>}</Card></div><section className={css.publish}><div><strong>{dirty?'Cambios pendientes':'Todo publicado'}</strong><small>Revisión {state.revision} · {date(state.updated_at)}</small></div><label>Motivo del cambio<input value={note} onChange={e=>setNote(e.target.value)} maxLength={180} placeholder="Ej. Pausar el juego por mantenimiento"/></label><button onClick={async()=>{if(!dirty||confirm('¿Descartar el borrador y cargar la configuración vigente?')){await loadState();setNote('');}}}>Recargar</button><button className={css.primary} disabled={!dirty||busy||note.trim().length<3} onClick={save}>{busy?'Publicando…':'Publicar cambios'}</button></section></>}
 {tab==='history'&&<Card title="Registro de publicaciones" sub="Cada cambio conserva su configuración. Restaurar prepara un borrador; debes publicarlo para aplicarlo.">{history.length?<div className={css.tableWrap}><table><thead><tr><th>Revisión</th><th>Fecha</th><th>Motivo</th><th>Acción</th></tr></thead><tbody>{history.map(h=><tr key={h.revision}><td>#{h.revision}</td><td>{date(h.created_at)}</td><td>{h.note}</td><td><button onClick={()=>{if(dirty&&!confirm('¿Reemplazar el borrador actual?'))return;setDraft(h.config);setNote('Restaurar revisión '+h.revision);setTab('controls');}}>Preparar restauración</button></td></tr>)}</tbody></table></div>:<Empty/>}</Card>}
 {tab==='health'&&<div className={css.grid}><Card title="Estado de la medición"><dl className={css.diagnostics}><dt>Base de datos / última consulta</dt><dd>{data?date(data.generatedAt):'Sin confirmar'}</dd><dt>Último evento recibido</dt><dd>{date(data?.lastEvent)}</dd><dt>Recepción de eventos</dt><dd>{state?.config.analyticsEnabled?'Activada':'Pausada'}</dd><dt>Retención programada</dt><dd>90 días · requiere cron instalado</dd><dt>Configuración publicada</dt><dd>Revisión {state?.revision}</dd></dl><p>Sin eventos nuevos puede significar falta de visitas autorizadas, un bloqueo del navegador o un problema de integración. Una gráfica vacía por sí sola no demuestra una caída.</p></Card><Card title="Experiencia de carga" sub="Percentil 75 de muestras disponibles. No todos los navegadores emiten estas métricas.">{data?.vitals.length?<dl className={css.diagnostics}>{data.vitals.map(v=><div key={v.name}><dt>{v.name==='LCP'?'LCP · contenido principal':'CLS · estabilidad visual'}</dt><dd>{number(v.value)}{v.name==='LCP'?' ms':''} · {number(v.samples)} muestras</dd></div>)}</dl>:<Empty/>}</Card><Card title="Herramientas de administración"><p><a href="/admin/hero">Abrir Hero Studio →</a></p><p><a href="/desk">Abrir Desk →</a></p><p>Acceso compartido con la contraseña de Hero Studio, sesión de ocho horas, protección de origen para publicaciones y bloqueo de intentos de acceso repetidos.</p></Card><Card title="Alcance y calidad"><p>Analítica propia con consentimiento; no sustituye los registros de infraestructura. Sin grabación de pantalla, mapas de calor individuales, IP almacenada en eventos ni valores de formularios.</p><p>La retención se ejecuta diariamente mediante una tarea autenticada. Comprueba sus ejecuciones en Vercel. Los clics no prueban conversiones y la medición del navegador no constituye una auditoría antifraude.</p></Card></div>}
 <footer className={css.footer}>WOJAKMETER · THE CRYPTO EMOTION INDEX <span>Control Center v01</span></footer></main></>}
 </div>;
}
