import Head from "next/head";
import { useEffect, useState } from "react";
const descriptions = {"frustration": "Pressure has given way to frustration and exhaustion.", "concern": "Fear is spreading, and confidence is under pressure.", "doubt": "Mixed signals. Neither direction has earned conviction.", "neutral": "A moment of balance while the market waits for direction.", "optimism": "Confidence is building, but conviction is still taking shape.", "content": "Steady confidence and a more constructive mood.", "euphoria": "Confidence is reaching extremes. Excitement can also signal excess."};
const tones = {frustration:'#E4485C',concern:'#E8848F',doubt:'#E8B4BA',neutral:'#B8C0CB',optimism:'#A8E6BF',content:'#7FD9A0',euphoria:'#3BD97A'};
export default function Introduction(){
 const [emotion,setEmotion]=useState('optimism');
 useEffect(()=>{
  // Preserve previously shared dashboard anchors and game links.
  const oldAnchors=['#market','#top-coins','#bagMoodSection','#emotionRadarSection','#wojak-studio','#emotionRush','#moodSection','#emotionScale'];
  if(oldAnchors.includes(window.location.hash)||new URLSearchParams(window.location.search).has('play'))
   window.location.replace('/dashboard'+window.location.search+window.location.hash);
 },[]);
 const tone=tones[emotion]; const glow=[1,3,5].map(i=>parseInt(tone.slice(i,i+2),16)).join(',');
 return <><Head>
 <title>WojakMeter — The market has a face.</title>
 <meta name="description" content="Understand crypto market sentiment at a glance. Explore WojakMeter, the Crypto Emotion Index, through a living 3D character." />
 <link rel="canonical" href="https://wojakmeter.com/" />
 <link rel="icon" href="/favicon.png?v=2" />
 <link rel="stylesheet" href="https://api.fontshare.com/v2/css?f[]=general-sans@400,500,600,700&display=swap" />
 <meta property="og:title" content="WojakMeter — The market has a face." />
 <meta property="og:description" content="See how the crypto market feels. The Crypto Emotion Index." />
 <meta property="og:url" content="https://wojakmeter.com/" />
 <meta property="og:type" content="website" />
 <meta property="og:image" content="https://wojakmeter.com/assets/hero/classic/optimism.png" />
 </Head><div id="wm-introduction" style={{'--accent':tone,'--emotion-glow':glow}}>
<header ><a href="#" aria-label="WojakMeter home"><img src="/assets/logo/wojakmeter_logo.png" alt="WojakMeter" /></a><nav ><a href="#how">{"How it works"}</a><a className="lp-navcta" href="/dashboard">{"Open dashboard \u2197"}</a></nav></header>
<main ><section className="lp-hero"><div ><div className="lp-eyebrow">{"The Crypto Emotion Index"}</div><h1 >{"The market"}<br  />{"has a "}<span >{"face."}</span></h1><p className="lp-lede">{"Understand crypto market sentiment at a glance through a living, expressive 3D character."}</p><div className="lp-actions"><a className="lp-primary" href="/dashboard">{"Explore the market "}<span >{"\u2197"}</span></a><a className="lp-secondary" href="#how">{"How it works \u2193"}</a></div></div><div className="lp-art"><img id="character" src={`/assets/hero/classic/${emotion}.png`} alt={`WojakMeter character expressing ${emotion}`} fetchPriority="high" width="1254" height="1254" /><div className="lp-caption"><span >{"EMOTION PREVIEW"}</span><span >{" / "}</span><b id="emotion-name">{emotion.charAt(0).toUpperCase()+emotion.slice(1)}</b></div></div></section>
<section className="lp-spectrum" aria-label="Explore seven emotions"><div className="lp-section-top"><h2 >{"One character. Seven ways to feel."}</h2><p >{"Select an emotion to explore the spectrum."}</p></div><div className="lp-moods" id="moods"><button className="lp-mood" data-emotion="frustration" style={{"--tone": "#E4485C"}} aria-pressed={emotion === "frustration"} type="button" onClick={() => setEmotion("frustration")}><b ><img className="lp-emotion-icon" src="/assets/icons/classic/frustration.png" alt="" aria-hidden="true" />{"Frustration"}</b><small >{"0\u201319"}</small></button><button className="lp-mood" data-emotion="concern" style={{"--tone": "#E8848F"}} aria-pressed={emotion === "concern"} type="button" onClick={() => setEmotion("concern")}><b ><img className="lp-emotion-icon" src="/assets/icons/classic/concern.png" alt="" aria-hidden="true" />{"Concern"}</b><small >{"20\u201334"}</small></button><button className="lp-mood" data-emotion="doubt" style={{"--tone": "#E8B4BA"}} aria-pressed={emotion === "doubt"} type="button" onClick={() => setEmotion("doubt")}><b ><img className="lp-emotion-icon" src="/assets/icons/classic/doubt.png" alt="" aria-hidden="true" />{"Doubt"}</b><small >{"35\u201344"}</small></button><button className="lp-mood" data-emotion="neutral" style={{"--tone": "#B8C0CB"}} aria-pressed={emotion === "neutral"} type="button" onClick={() => setEmotion("neutral")}><b ><img className="lp-emotion-icon" src="/assets/icons/classic/neutral.png" alt="" aria-hidden="true" />{"Neutral"}</b><small >{"45\u201359"}</small></button><button className="lp-mood" data-emotion="optimism" style={{"--tone": "#A8E6BF"}} aria-pressed={emotion === "optimism"} type="button" onClick={() => setEmotion("optimism")}><b ><img className="lp-emotion-icon" src="/assets/icons/classic/optimism.png" alt="" aria-hidden="true" />{"Optimism"}</b><small >{"60\u201369"}</small></button><button className="lp-mood" data-emotion="content" style={{"--tone": "#7FD9A0"}} aria-pressed={emotion === "content"} type="button" onClick={() => setEmotion("content")}><b ><img className="lp-emotion-icon" src="/assets/icons/classic/content.png" alt="" aria-hidden="true" />{"Content"}</b><small >{"70\u201384"}</small></button><button className="lp-mood" data-emotion="euphoria" style={{"--tone": "#3BD97A"}} aria-pressed={emotion === "euphoria"} type="button" onClick={() => setEmotion("euphoria")}><b ><img className="lp-emotion-icon" src="/assets/icons/classic/euphoria.png" alt="" aria-hidden="true" />{"Euphoria"}</b><small >{"85\u2013100"}</small></button></div><p id="description" aria-live="polite" style={{"color": "var(--muted)", "fontSize": "13px", "lineHeight": "1.7", "minHeight": "44px"}}>{descriptions[emotion]}</p></section>
<section className="lp-about" id="how"><div className="lp-eyebrow">{"From signals to sentiment"}</div><h2 style={{"marginTop": "20px"}}>{"A clearer first look"}<br  />{"at a complicated market."}</h2><p className="lp-intro">{"Price tells you what moved. WojakMeter brings market signals together into an emotional reading you can explore."}</p><div className="lp-steps"><article className="lp-step"><span className="lp-num">{"01 / OBSERVE"}</span><h3 >{"Read the signals."}</h3><p >{"Market movement, volume and sentiment provide context for the current reading."}</p></article><article className="lp-step"><span className="lp-num">{"02 / INTERPRET"}</span><h3 >{"Find the mood."}</h3><p >{"An index from 0 to 100 places the market on a spectrum from frustration to euphoria."}</p></article><article className="lp-step"><span className="lp-num">{"03 / EXPLORE"}</span><h3 >{"See it come to life."}</h3><p >{"On the dashboard, expression and movement turn that reading into a character you can understand at a glance."}</p></article></div></section>
<section className="lp-features"><div ><div className="lp-eyebrow">{"Look beyond the number"}</div><h2 style={{"marginTop": "20px"}}>{"The market."}<br  />{"Your bag."}<br  />{"The next shift."}</h2><p >{"Start with the big picture. Then explore the parts of the market that matter to you."}</p></div><div ><article className="lp-feature"><h3 >{"Market overview"}</h3><p >{"Explore the current emotion alongside market data and historical readings."}</p></article><article className="lp-feature"><h3 >{"Bag Mood"}</h3><p >{"See your portfolio through the same emotional spectrum."}</p></article><article className="lp-feature"><h3 >{"Reactive tokens"}</h3><p >{"Explore individual Solana tokens and how their market activity translates into mood."}</p></article></div></section>
<section className="lp-closing"><div ><h2 >{"What does the market"}<br  />{"feel like right now?"}</h2><p >{"Meet it on WojakMeter."}</p></div><a className="lp-primary" href="/dashboard">{"Open dashboard \u2197"}</a></section></main>
<footer ><div ><div className="lp-brand">{"WOJAKMETER"}</div><p >{"The Crypto Emotion Index."}</p></div><div className="lp-legal">{"Market sentiment is context, not a prediction."}<br  />{"For informational purposes. Not financial advice."}</div></footer></div></>;
}
